redamancy:
  appname: redamancy-template
  version: 0.0.1-beta
  features:
    - info-api
#    - tick
    - redis_cached

spring:
  datasource:
    username:
    password:
    url: jdbc:sqlite:test.db
    driver-class-name: org.sqlite.JDBC

  redis:
    database: 0
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: alpacredis
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000

  jpa:
    #    database: MySQL
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /**

server:
  port: 24020